branch-defaults:
  UpdatedBeanstalk:
    environment: mitlib-staging-proginfoscience
environment-defaults:
  mitlib-staging-proginfoscience:
    branch: null
    repository: null
global:
  application_name: mitlib-global-proginfoscience
  default_ec2_keyname: mit-dornera
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 7.2 running on
    64bit Amazon Linux/2.8.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
